#!/bin/bash

echo -n " 00 - Command/net check" | tee /dev/console $LOG

for i in echo wget ip tar gtkdialog grep sed date uname;do
if [ -z "$(which $i)" ];then
[ "$i" == "gcc" -o "$i" == "make" ]&& DEV="\t(devx sfs needed!)" || DEV=""
echo "    - Missing command:\t$i$DEV" >> $TMP/stop
fi
done
[ -z "$(ip addr show | grep "ine.*brd")" ]&& echo "    - No internet connection" >> $TMP/stop

if [ -e $TMP/stop ];then
echo "   [ERROR]" | tee /dev/console $LOG
cat $TMP/stop | tee /dev/console $LOG
else
echo "   [OK]" | tee /dev/console $LOG
fi


