#!/bin/bash

IFILE="/mnt/home/scriptek/1_OS_BUILDER/Test01/tmp/03_converted_database"
#IFILE="/mnt/home/scriptek/1_OS_BUILDER/test02/03_converted_database"
OFILE="/mnt/home/scriptek/1_OS_BUILDER/test02/03_converted_database2"

[ -e $OFILE ]&& rm $OFILE

cat $IFILE | sed -r '/PN:|VER:/s/$/\|/g' | tr -d '\n' |
sed 's/PN:/\n/g ; s/|SRC:/|/g ; s/VER:/\|/g ; 
s/|DEP:/|/g ; s/DESC:/\|/g ; s/CAT:/\|/g ;
s/PDIR:/\|/g ; s/SIZE:/\|/g' >> $OFILE

#declare -A entry=()
#cat $IFILE | while IFS=: read -r key value; do
# entry[$key]=$value
#  if [[ $key = SIZE ]]; then
#  printf '%s|%s|%s|%s|%s|%s|%s\n' "${entry[PN]}" "${entry[VER]}" "${entry[DEP]}" "${entry[DESC]}" "${entry[CAT]}" "${entry[PDIR]}" "${entry[SIZE]}" >> $OFILE
#  entry=()
#  fi
# done
 
 
#declare -A entry=(); while IFS=: read -r key value; do entry[$key]=$value; if [[ $key = SIZE ]]; then printf '%s|%s|%s|%s|%s|%s|%s\n' "${entry[PN]}" "${entry[VER]}" "${entry[DEP]}" "${entry[DESC]}" "${entry[CAT]}" "${entry[PDIR]}" "${entry[SIZE]}"; entry=(); fi; done < <(curl -s pastebin.com/raw/tRcUpD92 | tr -d '\r'; echo)