#!/bin/bash

BNAME="Puppy Builder CE"
OWN_PID="$$"

export BD="$(dirname $0)"
export TMP="$BD/tmp"
export SRC_DIR="$BD/sources"

[ ! -e $TMP ]&& mkdir -p $TMP || rm $TMP/*

DATE="$(date +'y%Y m%m d%d %H:%M')"
LOG="$BD/puppy-builder.log"
echo "
 $BNAME - $DATE 
" > $LOG

if [ ! -t 0 ];then
echo " HIBA: Indítsd terminálból az építőt!" >> $LOG
touch $TMP/stop
fi

export PBCE='<window width_request="400" height_request="400"title="'$BNAME'">
<vbox scrollable="true">
<text auto-refresh="true">
<input file>'$LOG'</input>
</text>
</vbox></window>'

gtkdialog --program=PBCE &

for script in $BD/scripts/* ;do
[ ! -e $TMP/stop ]&& . $script || break
done

if [ -e $TMP/stop ];then
echo -e "\n ########################\n\n Építési folyamat megállítva." >> $LOG
 if [ ! -z "$(cat $TMP/stop)" ];then
 MESS='$(cat $LOG)'
 clear
 echo "$MESS"
 xmessage "$MESS" --center
 fi
exit
else
echo -e "\n ########################\n\n Építési folyamat sikeresen befejeződött." >> $LOG
fi
