#!/bin/sh

DD="$TMP/distros"

[ ! -d $DD ]&& mkdir -p $DD

echo -n " 01 - System base settings" | tee /dev/console $LOG

for i in "$LINKS";do
if [ -z "$(wget --spider --server-response $i 2>&1 | grep '200 OK')" ];then
 echo -e "   - URL not found or no exits: $i"
 echo "    $(wget --spider --server-response $i 2>&1 | grep 'HTTP/' | cut -f4- -d' ')"
 echo
else
 if [ "${i##*/}" != "huge_kernels" ];then
 DISTRO="$(cut -f4 -d/ <<< "$i")"
 echo " Download '$DISTRO' active codenames..."
 wget -q -O- "$i"| grep 'href' | sed 's/<[^>]*>//g' |
 grep -v '[a-z]\-[a-z]\|^P\|^ \|^I\|^R' | sed 's:/ *:|: ; s: [0-9].*$::' > "$DD/$DISTRO"
 else
 echo " Download 'huge kernel' list..."
 wget -q -O- "$i"| grep 'href' | cut -f4,7,9 -d'>' | grep "bz2<" |
 sed 's:</a>\|</td>:|:g ; s:</td.*:: ; s: [0-9].*|:|: ; s:$:b:' > $TMP/kernel_list
 fi
fi
done

while [ ! "$ARCH" ];do
echo -e " Target arhictecture:\n\n   1)	x86	32bit\n   2)	amd64	64bit\n"
read -p " Choose number: " ARCH
echo
if [ "$ARCH" == '1' ];then ARCH=i386
elif [ "$ARCH" == '2' ];then ARCH=amd64
else ARCH=''
fi
done
echo $ARCH