#!/bin/sh

FILE="$SRC_DIR/Sources"
#FILE2="$DIR/Sources_grep_package_sel"

echo -e "\n 03 - Csomagok Kiválasztása" >> $LOG

FULL="$(cat $FILE | grep -n . | grep "Package: \|:Version: " |
 sed 's/^/::/ ; s/::[0-9]*:Version: / /' | tr -d '\n' |
 sed 's/::/\n/g ; s/Package://g' | sed '1 d')"

while : ;do
 SELECT=''
 echo && echo -ne " Kereső használat: (kisbetű,szám vagy kötőjel)
   (minimum 3 karakter) (all = összes csomag kiírása)
   (h = segítség) (q = kilépés)\n
 Csomag keresése: " && read i
 [ "$i" == 'q' ]&& break
 [ "$i" == 'h' ]&&\
 echo -e "\nAjánlott minimum csomaglista:
bash busybox coreutils disktype fuse gzip kmod
libgcc libglib2.0 libglib2.0-bin libglib2.0-data
mingetty ncurses-base readline-common sed udev
unzip util-linux zip zlib1g" && continue
 if [ "${#i}" -gt '2' ];then
  echo
  if [ "$i" == 'all' ];then
   SELECT="$(echo "$FULL" | grep -n .)"
   else
   SELECT="$(echo "$FULL" | grep " .*$i.*" | grep -n .)"
  fi
  if [ "$SELECT" ];then
  echo "$SELECT" | sed 's/:[0-9]*:/:/g'
  echo && echo -ne " Válassz számot a hozzáadáshoz. pl 6 vagy 1 12 45 ...
   (enter = vissza a kereséshez) (q = kilépés)
   (all = összes elem hozzáadása)\n\n Adj meg valamit: "
  read i2
  [ "$i2" == '' ]&& continue
  [ "$i2" == 'q' ]&& break
  [ "$i2" == 'all' ]&& i2="$(cut -f1 -d: <<< "$SELECT")"
   for nums in $i2;do
   [ "$(grep "^$nums:" <<< "$SELECT")" ]&& grep "^$nums:" <<< "$SELECT" # kiíratás
   done
  else
  echo "Nincs találat"
  fi
 else
 echo "Adj meg minimum 3 karaktert..."
 fi
done
